eProject3/Areas/Admin/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using eProject3.Common;
using eProject3.Model.Common;
using eProject3.Model.DAL;

namespace eProject3.Areas.Admin.Controllers
{
    public class ClientsController : BaseController
    {
        private Project3DbContext db = new Project3DbContext();

        // GET: Admin/Clients
        public ActionResult Index()
        {
            CountMessage();
            CountOrder();
            return View(db.Client.Where(x => !x.IsDeleted).OrderByDescending(x => x.CreatedOn).ToList());
        }

        // GET: Admin/Clients/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Client.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // GET: Admin/Clients/Create
        public ActionResult Create()
        {
            CountMessage();
            CountOrder();
            return View();
        }

        // POST: Admin/Clients/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,UrlImage,Address,Email,Phone,CreatedOn,CreatedBy,ModifiedOn,ModifiedBy,IsDeleted")] Client client)
        {
            if (ModelState.IsValid)
            {
                client.Id = Guid.NewGuid();
                AuditTable.InsertAuditFields(client);
                var session = (UserLogin)Session[CommonConstants.USER_SESSION];
                client.CreatedBy = session.UserName;
                db.Client.Add(client);
                db.SaveChanges();
                SetAlert("Thêm mới thành công", "success");
                return RedirectToAction("/Admin/Clients");
            }

            return View(client);
        }

        // GET: Admin/Clients/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Client.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // POST: Admin/Clients/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,UrlImage,Address,Email,Phone,CreatedOn,CreatedBy,ModifiedOn,ModifiedBy,IsDeleted")] Client client)
        {
            if (ModelState.IsValid)
            {
                AuditTable.UpdateAuditFields(client);
                var session = (UserLogin)Session[CommonConstants.USER_SESSION];
                client.ModifiedBy = session.UserName;
                db.Entry(client).State = EntityState.Modified;
                db.SaveChanges();
                SetAlert("Cập nhật thành công", "success");
                return Redirect("/Admin/Clients");
            }
            return View(client);
        }

        // GET: Admin/Clients/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Client.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // POST: Admin/Clients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Client client = db.Client.Find(id);
            client.IsDeleted = true;
            db.SaveChanges();
            return RedirectToAction("/Admin/Clients");
        }
    }
}

eProject3/Controllers/BusinessesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using eProject3.Model.DAL;

namespace eProject3.Controllers
{
    public class BusinessesController : Controller
    {
        private Project3DbContext db = new Project3DbContext();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetBusiness()
        {
            List<Business> businesses = new List<Business>();
            businesses = db.Business.Where(x => !x.IsDeleted).OrderByDescending(x => x.CreatedOn).Take(4).ToList();
            ViewBag.Count = businesses.Count();
            return PartialView(businesses);
        }

        public ActionResult Detail(Guid id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Business business = db.Business.Find(id);
            if (business == null)
            {
                return HttpNotFound();
            }
            return View(business);
        }

        public ActionResult GetInvolve(Guid? id)
        {
            Business business = db.Business.Find(id);
            List<Business> businesses = new List<Business>();
            businesses = db.Business.Where(x => x.Id != business.Id && !x.IsDeleted).OrderByDescending(x => x.CreatedOn).Take(3).ToList();
            ViewBag.Count = businesses.Count();
            return PartialView(businesses);
        }
    }
}

eProject3/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using eProject3.Model.DAL;

namespace eProject3.Controllers
{
    public class ClientsController : Controller
    {
        private Project3DbContext db = new Project3DbContext();

        // GET: Clients
        public ActionResult Index()
        {
            List<Client> clients = new List<Client>();
            clients = db.Client.Where(x => !x.IsDeleted).Take(3).ToList();
            ViewBag.Count = clients.Count();
            return PartialView(clients);
        }

        public ActionResult Detail(Guid id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Client.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }
    }
}

eProject3/Views/Clients/Detail.cshtml
@model eProject3.Model.DAL.Client

@{
    ViewBag.Title = "Chi tiết khách hàng";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .imageDetail {
        transition: all .4s ease-in-out;
    }

        .imageDetail:hover {
            transform: scale(1.4);
        }
</style>
<!--start-breadcrumbs-->
<div class="breadcrumbs">
    <div class="container">
        <div class="breadcrumbs-main">
            <ol class="breadcrumb">
                <li><a href="/Home">Trang chủ</a></li>
                <li class="active">@ViewBag.Title</li>
            </ol>
        </div>
    </div>
</div>
<!--end-breadcrumbs-->
<!--start-single-->
<div class="single contact">
    <div class="container">
        <div class="single-main">
            <div class="col-md-9 single-main-left">
                <div class="sngl-top">
                    <div class="col-md-5 single-top-left">
                        <div class="flexslider">
                            <ul class="slides">
                                <li data-thumb="images/s1.jpg">
                                    <img src="@Model.UrlImage" class="imageDetail" />
                                </li>
                            </ul>
                        </div>
                        <!-- FlexSlider -->
                        <script defer src="~/Content/Client/js/jquery.flexslider.js"></script>
                        <link rel="stylesheet" href="~/Content/Client/css/flexslider.css" type="text/css" media="screen" />

                        <script>
                            // Can also be used with $(document).ready()
                            $(window).load(function () {
                                $('.flexslider').flexslider({
                                    animation: "slide",
                                    controlNav: "thumbnails"
                                });
                            });
                        </script>
                    </div>
                    <div class="col-md-7 single-top-right">
                        <div class="details-left-info simpleCart_shelfItem">
                            <h3>@Model.Name</h3>
                            <h2 class="quick">Mô tả:</h2>
                            <p class="quick_desc">@Html.Raw(Model.Email)</p>
                            <p class="quick_desc">@Html.Raw(Model.Address)</p>
                            <p class="quick_desc">@Html.Raw(Model.Phone)</p>
                            <div class="clearfix"> </div>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="latest products">
                    <div class="product-one">
                        @*@{ Html.RenderAction("GetInvolve", "Businesses");}*@
                        <div class="clearfix"> </div>
                    </div>
                </div>
            </div>
            <div class="col-md-3 single-right">
                <h3>Thương hiệu</h3>
                <ul class="product-categories">
                    @*@{ Html.RenderAction("GetAllCategory", "Product");}*@
                </ul>
            </div>
            <div class="clearfix"> </div>
        </div>
    </div>
</div>

eProject3/Views/Clients/Index.cshtml
@model IEnumerable<eProject3.Model.DAL.Client>
@if ((int)ViewBag.Count > 0)
{
    foreach (var item in Model)
    {
        var url = "/Clients/Detail/" + item.Id;
        <div class="col-md-4 abt-shoe-left" style="height: 400px;">
            <div class="abt-one" style="height: 400px;">
                <a href="@url"><img src="@item.UrlImage" width="350" height="220" alt="" /></a>
                <h4><a href="@url">@item.Name</a></h4>
                <div class="content">
                    @Html.Raw(item.Address)
                </div>
                <a href="@url">Xem chi tiết</a>
            </div>
        </div>
    }
}